# Dockerfile for System Dashboard

# Nginx Alpine base image
FROM nginx:alpine

# Copy index.html
COPY index.html /usr/share/nginx/html

# Copy configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Port Mapping
EXPOSE 80
